### ISSUE TITLE
Missing blobs + soft reboots

### ISSUE THREAD

**Issue by pavanpaps** [yaap/device_xiaomi_raphael#3]
at the time of writing this

12-25 14:43:27.028  1086  1086 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wfdhdcphalservice": library "libwfdhdcpcp.so" not found: needed by main executable
12-25 14:43:27.081  1136  1136 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wfdvndservice": library "libwfdhdcpcp.so" not found: needed by /vendor/lib/libwfdhdcpservice_proprietary.so in namespace (default)
12-25 14:43:27.091  1091  1091 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wifidisplayhalservice": library "libwfdhdcpcp.so" not found: needed by /vendor/lib/libwfdmodulehdcpsession.so in namespace (default)
06-05 19:57:11.322  1857  1857 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wfdhdcphalservice": library "libwfdhdcpcp.so" not found: needed by main executable
06-05 19:57:11.332  1862  1862 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wifidisplayhalservice": library "libwfdhdcpcp.so" not found: needed by /vendor/lib/libwfdmodulehdcpsession.so in namespace (default)
06-05 19:57:11.466  1892  1892 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/wfdvndservice": library "libwfdhdcpcp.so" not found: needed by /vendor/lib/libwfdhdcpservice_proprietary.so in namespace (default)

few missing blobs and this is causing drm crash

+ not quite sure but latest changes are causing system to freeze and soft reboots when taking logcats (assuming kernel changes).

edit: blob edits were fpushed so that isn't an issue now but soft reboots still persistent.

**Comment by poad42** [comment]
The blobs issue is sorted, I haven't done anything special in kernel other than to upstream, have been using and debugging all day no soft reboots. Maybe something on your platform?

**Comment by pavanpaps** [comment]
had checked out a yaap test build sent by @Lacentix few hrs ago, faced the same issue on it. 
Basically did 
> adb shell
> logcat
on my pc, phone froze for a good few seconds and rebooted
Also, flashed a custom kernel for good measure and issue was mitigated

**Comment by poad42** [comment]
https://github.com/yaap/kernel_xiaomi_sm8150/commit/9c2361a6c8e8a57814313179a70f38366e8b8f8f

Was because if this.
